name: Greeting on variable day

on:
  push

env:
  DAY_OF_WEEK: Monday
  BEFORE_JOBS: before___job
jobs:
  greeting_job:
    runs-on: ubuntu-latest
    env:
      Greeting: Hello
      Inside_Job: inside___job
    steps:
      - name: "Say Hello Mona it's Monday"
        run: echo "$Greeting $First_Name. Today is $DAY_OF_WEEK! + $BEFORE_JOBS + $Inside_Job +$Inside_steps + ${{ vars.NEW_VAR_1 }} "
        env:
          First_Name: Mona
          Inside_steps: Inside_____steps
